[build]
  environment = { NODE_VERSION = "14.17.6" }

[context.production]
  environment = { SANITY_STUDIO_API_DATASET= 'production' }
  NODE_ENV = "production"
  
[context.staging]
  environment = { SANITY_STUDIO_API_DATASET= 'staging' }
  NODE_ENV = "development"

[context.branch-deploy]
  environment = { SANITY_STUDIO_API_DATASET= 'staging' }
  NODE_ENV = "development"
  