[build]
  environment = { NODE_VERSION = "14.17.6" }

[context.staging]
  environment = { GRIDSOME_SANITY_DATASET = 'staging' }
  NODE_ENV = "development"

[context.branch-deploy]
  environment = { GRIDSOME_SANITY_DATASET = 'staging' }
  NODE_ENV = "development"
  